# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 205e007dad7059de8207a2167f237e12d99c6d2929852422e689235814d03a9d58781a9f548884e28fef453e4556d159ba35be6ca1880217abbee04c77181192

test:
  secret_key_base: 3e35de320473ed5729e2006d50ed14607e5b16689d7ab77fad666094b4e95a95ee29d67fe9a17577545012236ded2405e62f75aa6e75d6f0dd8337c4a1dd596d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
